--- GRANT PRIVILEGES TO APPUSER

GRANT ALL ON SCHEMA ${flyway:defaultSchema} TO ${appuser} WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES IN SCHEMA ${flyway:defaultSchema}
GRANT ALL ON TABLES TO ${appuser} WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES IN SCHEMA ${flyway:defaultSchema}
GRANT ALL ON SEQUENCES TO ${appuser} WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES IN SCHEMA ${flyway:defaultSchema}
GRANT EXECUTE ON FUNCTIONS TO ${appuser} WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES IN SCHEMA ${flyway:defaultSchema}
GRANT USAGE ON TYPES TO ${appuser} WITH GRANT OPTION;


-- CREATE ACCOUNT_BOOK TABLE

CREATE TABLE ACCOUNT_BOOK
(
    "ID" serial,
    "CODE" character varying(15) NOT NULL,
    "JURISDICTION" character varying(15),
    "NAME" character varying(63),
    "DESCRIPTION" character varying(127),
    "SEQUENCE_NR" integer DEFAULT 0,
    "FLAGS" integer,
    CONSTRAINT "PK_ACCOUNT_BOOK" PRIMARY KEY ("ID"),
    CONSTRAINT "UK_ACCOUNT_BOOK_CODE_JURISDICTION" UNIQUE ("CODE", "JURISDICTION")
)

TABLESPACE pg_default;

ALTER TABLE ACCOUNT_BOOK OWNER to ${flyway:user};
