ALTER TABLE ${flyway:defaultSchema}.TRANSACTION
    ADD COLUMN "TRAN_TIMESTAMP" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;


CREATE INDEX "IDX_TRANSACTION_TIMESTAMP"
    ON ${flyway:defaultSchema}.TRANSACTION USING btree
    ("TRAN_TIMESTAMP" ASC NULLS LAST);

-- ADD INDEX TO ACCOUNT

CREATE INDEX "IDX_ACCOUNT_SEARCH"
    ON ${flyway:defaultSchema}.ACCOUNT USING btree
    ("CHART" ASC NULLS LAST, "CODE" ASC NULLS LAST);
